"""Added a foreign key to comments table

Revision ID: 10c65edf14da
Revises: ef4a2dc06ad7
Create Date: 2022-05-16 15:48:19.796791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c65edf14da'
down_revision = 'ef4a2dc06ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('authors', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['authors'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'authors')
    # ### end Alembic commands ###
