"""altered some parts

Revision ID: 1d4b90a77436
Revises: 2b50b6f3862d
Create Date: 2022-05-17 13:42:39.520998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4b90a77436'
down_revision = '2b50b6f3862d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('author', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'author')
    # ### end Alembic commands ###
