"""Changed the tablename Blogs to blogs

Revision ID: c3b76dc28da0
Revises: a4b12c3135a2
Create Date: 2022-05-15 12:47:43.464049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b76dc28da0'
down_revision = 'a4b12c3135a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Blogs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Blogs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Blogs_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('blog', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Blogs_pkey')
    )
    op.drop_table('blogs')
    # ### end Alembic commands ###
