"""Added a foreign key to blogs table

Revision ID: ef4a2dc06ad7
Revises: 3c4b3f108326
Create Date: 2022-05-16 15:38:05.318658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4a2dc06ad7'
down_revision = '3c4b3f108326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'users', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'author')
    # ### end Alembic commands ###
